name: Test Project
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   name: Get Code
                uses: actions/checkout@v3.5.3
            -   name: Setup NodeJs
                uses: actions/setup-node@v2.5.2
                with:
                    node-version: 18
            -   name: Install dependencies
                run: npm ci
            -   name: Run tests
                run: npm test
